### ISSUE TITLE
Meteo-qt apparent malfunction

### ISSUE THREAD

**Issue by Langjan** [dglent/meteo-qt#114]
The dropdown menu of Meteo-qt on my Ubuntu 20.04 Unity desktop and also same OS on my laptop used to have an option "toggle window" which opened a window that shows the current day's expected temperatures and rainfall by the hour in addition to the other forecasts. This option has disappeared, rendering meteo-q virtually useless. I have tried to re-install the app to no avail. Can you help please?

**Comment by dglent** [comment]
Could you give me the output of the command below ?
Open the python interpreter and type:
``` Python
import os
os.environ.get('DESKTOP_SESSION')
```
For exemple in my pc with LXQt
```[dglent@localhost ~]$ python
Python 3.8.9 (default, Apr  5 2021, 18:09:13) 
[GCC 10.2.1 20210130] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> os.environ.get('DESKTOP_SESSION')
'/usr/share/xsessions/lxqt'
>>> 
```

**Comment by dglent** [comment]
If the output is in this list: ['unity', 'ubuntu', 'budgie-desktop'],  you should see the "Toggle window" menu entry.
i have asked and the name has not been changed in Unity desktop
https://github.com/dglent/meteo-qt/blob/8d3572e97c045ea34d66783e4314c724a021bb08/meteo_qt/meteo_qt.py#L118
But it would be useful to understand the problem.
It is ok with you the above instructions in order to see the session name ?
Don"t hesitate to tell me if you need some help.

**Comment by dglent** [comment]
I installed Ubuntu and meteo-qt
I cannot reproduce the issue
With click on the icon i see the context menu and i have the option to toggle the windows

![εικόνα](https://user-images.githubusercontent.com/4337756/132824850-f6f716ec-68df-4ca4-b1a1-8ff7297c42b3.png)

**Comment by dglent** [comment]
Which version of meteo-qt do you have ?
The latest is 2.4

**Comment by Langjan** [comment]
Thanks Dimitrios, I have settled into using My-Weather-Indicator, 
Meteo-q is too finicky.

Jan Greeff
Tuintuiste 75, Posbus 3575, Bela Bela 0480
Tel. Jan 084 548 3890 Juanita 072 279 0298
Gesondheid sonder grense: https://verslank.net/
Jy verloor nooit deur lief te hê nie. Jy verloor altyd deur terug te hou.
