### ISSUE TITLE
Very low contrast against a semi-dark background window

### ISSUE THREAD

**Issue by ghost** [dglent/meteo-qt#75]
on an Arch Fluxbox system with Qt (5.10) theme managed by `qt5ct` as can be seen in the attachment.
![meteo](https://user-images.githubusercontent.com/1426842/34911601-bdf7ebc0-f8c5-11e7-8cde-45f14242ebc3.jpg)

**Comment by dglent** [comment]
Hello,

Thanks for inform me about this.
I will do something for this, maybe an option to chose, but not shortly a little bit later

**Comment by AcarBurak** [comment]
Thank you. Thanks a lot as well for the very fine gift, meteo-qt.

**Comment by dglent** [comment]
I am about to think if it is better to have an option to choose the colour or leave it as default (black) and leave the theme apply its savour.

Maybe is better to have a contrast for the central details (Wind, Cloudiness, Pressure, Humidity ...)
In the case, an option is needed in order to choose the colour.

**Comment by dglent** [comment]
Fixed in 1.0.0
